#include <stdio.h>
#include <string.h>
#include<stdint.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

int main(const int nargs, char const* const args[])
{
  if(nargs!=3) {
    fprintf(stderr,"Usage: %s concatenateddicevalues file|-\n", args[0]);
    return 1;
  }

  const int nb6s=strlen(args[1]);
  uint8_t b6vals[nb6s];
  int i;

  for(i=nb6s-1; i>=0; --i) {

    if(args[1][i] < 0x31 || args[1][i] > 0x36) {
      fprintf(stderr,"%s: Error: Dice value '%c' is invalid!\n", args[0], args[1][i]);
      return 1;
    }
    b6vals[i] = args[1][i] - 0x31;
  }

  const int nmaxbytes=(int)((2.585*nb6s)*0.125+0.5); //~ ceil(ln6/ln2 * nb6s / 8)
  int byte=nmaxbytes-1;
  int firstb6=0;
  uint8_t bit=0;
  uint8_t bytes[nmaxbytes]; //~ ceil(ln6/ln2 * nb6s / 8)

  memset(bytes, 0, nmaxbytes);

  while(firstb6<nb6s) {

    if(b6vals[nb6s-1] & 0x1) bytes[byte]|=1<<bit;
    ++bit;

    if(bit==8) {
      bit=0;
      --byte;
    }
    (b6vals[nb6s-1])>>=1;

    //Divide base 6 number by 2
    for(i=nb6s-2; i>=firstb6; --i) {

      if(b6vals[i] & 0x1) b6vals[i+1] += 3;
      (b6vals[i])>>=1;
    }

    if(b6vals[firstb6]==0) ++firstb6;
  }

  if(bit!=7) ++byte;


  int fd = (strlen(args[2])==1 && args[2][0]=='-'? STDOUT_FILENO: open(args[2], O_WRONLY|O_CREAT, S_IRUSR|S_IWUSR));

  if(fd < 0) {
    perror("open");
    return 1;
  }

  const int nbytes=nmaxbytes-byte;

  if(write(fd, bytes+byte, nbytes) != nbytes) {
    perror("write");
    return 1;
  }

  if(fd != STDOUT_FILENO) printf("%i generated byte(s) (%i bits) of entropy\n",nbytes,nbytes*8);

  /*
  for(i=byte; i<nmaxbytes; ++i) printf("%01u%01u%01u%01u%01u%01u%01u%01u ",(bytes[i])>>7,((bytes[i])>>6)&1,((bytes[i])>>5)&1,((bytes[i])>>4)&1,((bytes[i])>>3)&1,((bytes[i])>>2)&1,((bytes[i])>>1)&1,bytes[i]&1);
  printf("\n");
  */
  return 0;
}
